tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                "background": "#f9faf6",
                "surface-container": "#eeeeea",
                "tertiary": "#592f35",
                "secondary-fixed-dim": "#a9d0af",
                "inverse-surface": "#2f312f",
                "surface-container-highest": "#e2e3df",
                "secondary": "#43664b",
                "on-secondary": "#ffffff",
                "on-primary-container": "#a7d0b1",
                "outline-variant": "#c1c8c0",
                "on-tertiary-fixed-variant": "#673a40",
                "tertiary-fixed": "#ffd9dc",
                "primary-fixed": "#c3edcd",
                "surface-dim": "#dadad6",
                "on-secondary-container": "#476b4f",
                "on-error-container": "#93000a",
                "surface-bright": "#f9faf6",
                "surface-container-lowest": "#ffffff",
                "surface-container-high": "#e8e8e4",
                "secondary-container": "#c2eac7",
                "on-surface-variant": "#414842",
                "on-secondary-fixed": "#00210d",
                "surface-variant": "#e2e3df",
                "primary-fixed-dim": "#a7d0b2",
                "on-primary-fixed": "#00210f",
                "on-background": "#1a1c1a",
                "primary-container": "#355a42",
                "inverse-primary": "#a7d0b2",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                "surface-container-low": "#f4f4f0",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#331016",
                "inverse-on-surface": "#f1f1ed",
                "tertiary-container": "#74454b",
                "on-primary-fixed-variant": "#294e37",
                "on-tertiary-container": "#f5b6bc",
                "tertiary-fixed-dim": "#f5b6bd",
                "primary": "#1e422c",
                "on-primary": "#ffffff",
                "outline": "#727972",
                "surface": "#f9faf6",
                "on-surface": "#1a1c1a",
                "secondary-fixed": "#c4ecca",
                "on-secondary-fixed-variant": "#2c4e35",
                "surface-tint": "#41664e",
                "error": "#ba1a1a"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "card": "20px",
                "full": "9999px"
            },
            "spacing": {
                "xxl": "48px",
                "sm": "8px",
                "sidebar_width": "280px",
                "md": "16px",
                "xxxl": "64px",
                "content_max_width": "1600px",
                "lg": "24px",
                "xl": "32px",
                "xs": "4px"
            },
            "fontFamily": {
                "label-sm": ["Inter"],
                "display-lg-mobile": ["Space Grotesk"],
                "body-lg": ["Inter"],
                "body-sm": ["Inter"],
                "headline-md": ["Space Grotesk"],
                "headline-sm": ["Space Grotesk"],
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "display-lg": ["Space Grotesk"]
            },
            "fontSize": {
                "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
                "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
          },
        },
      }
